### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "ghitz4",
    "email": "john@doe.com",
    "password": "qwe123"

}

### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "maria",
    "email": "maria@gmail.com",
    "password": "qwe123"

}


### Login Volunteer
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "anastasia7miron+maria@gmail.com",
    "password": "nastea123"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "baba@marusea.com",
    "password": "abcd12"
}


### Logout

POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### Profile

GET http://localhost:3000/api/profile
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### Profile Update
PUT http://localhost:3000/api/profile
Content-Type: application/json
Authorization: Bearer {{tokenV}}
{
    "username": "maria",
    "email": "maria@gamil.com",
    "type": "volunteer",
    "skills": "rapid si iute",
    "availability": "9-17"
}

### Profile Update
POST  http://localhost:3000/api/auth/complete
Content-Type: application/json
Authorization: Bearer {{tokenB}}

{
    "type": "beneficiary",
    "needs": "dupa cumparaturi",
    "location": "Botanica"
}

### Profile DELETE
DELETE  http://localhost:3000/api/profile
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### Create request as beneficiary
POST  http://localhost:3000/api/requests
Content-Type: application/json
Authorization: Bearer {{tokenB}}

{
    "title": "Ajutor",
    "description": "Am nevoie de ajutor la supermarket.",
    "urgency": "high",
    "location": "Strada Mihai Eminescu, 9"
}

### Requests GET
GET  http://localhost:3000/api/requests
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### Requests id
GET http://localhost:3000/api/requests/{{requestId}}
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### Update Requests id 
PUT http://localhost:3000/api/requests/{{requestId}}
Content-Type: application/json
Authorization: Bearer {{tokenB}}

### Update Requests Id Review
PUT http://localhost:3000/api/requests/{{requestId}}/review
Content-Type: application/json
Authorization: Bearer {{{{tokenV}}}}

### POST Leave a review for Request as Beneficiar
POST http://localhost:3000/api/requests/{{requestId}}/review
Content-Type: application/json
Authorization: Bearer {{tokenB}}

{

}

### POST Leave a review for Request as Volunteer
POST http://localhost:3000/api/requests/{{requestId}}/review
Content-Type: application/json
Authorization: Bearer {{tokenV}}

{
    
}


### POST Requests Id Accept
POST http://localhost:3000/api/requests/{{requestId}}/accept
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### POST Requests Id Cancel
POST http://localhost:3000/api/requests/{{requestId}}/cancel
Content-Type: application/json
Authorization: Bearer {{tokenB}}

### POST Requests Id Complete
POST http://localhost:3000/api/requests/{{requestId}}/complete
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### GET Volunteers
GET http://localhost:3000/api/volunteers
Content-Type: application/json
Authorization: Bearer {{tokenB}}

### GET Volunteers id
GET http://localhost:3000/api/volunteers/225a3473-efa8-48aa-92ff-291eaf9fb39c 
Content-Type: application/json
Authorization: Bearer {{tokenB}}

### GET Volunteers id requests
GET http://localhost:3000/api/volunteers/225a3473-efa8-48aa-92ff-291eaf9fb39c/requests
Content-Type: application/json
Authorization: Bearer {{tokenB}}

### GET Beneficiars
GET http://localhost:3000/api/beneficiars
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### GET Beneficiars id
GET http://localhost:3000/api/beneficiars/f605cf3c-36cd-40ac-b390-108135c6a82f
Content-Type: application/json
Authorization: Bearer {{tokenV}}

### GET Beneficiars id requests
GET http://localhost:3000/api/beneficiars/f605cf3c-36cd-40ac-b390-108135c6a82f/requests
Content-Type: application/json
Authorization: Bearer {{tokenV}}


### GET Reviews

GET  http://localhost:3000/api/reviews
Content-Type: application/json
Authorization: Bearer {{tokenV}}


### Password reset
POST http://localhost:3000/api/auth/password-recovery
Content-Type: application/json

{
    "email": "anastasia7miron+maria@gmail.com"
}

### Pasword Change
POST http://localhost:3000/api/auth/change-password
Content-Type: application/json

{
    "token": "bHPjkcAx5gFrmy4o",
    "newPassword": "nastea123"
}